;;;; testing.lisp

(in-package #:mnas-graph)

(view-graph 
 (generate-graph
  '(("noda-label-print" "*noda-print-number*" )
    ("x0" "noda-label-print")
    ("x-end" "noda-label-print")
    ("x-start" "noda-label-print")
    ("main" "x0")
    ("main" "x1")
    ("main" "x-start")
    ("main" "x-end")
    ("main" "x-preamble")
    ("main" "x-postamble")
    ("rib-print" "rib->rib-list")
    ("noda-list-print" "noda-print")
    ("noda-list-group-print" "noda-list-print")
    ("rib-print" "noda-list-group-print")
    ("rib-list-print" "rib-print")
    ("main" "rib-list-print")
    ("make-create" "main")
;;;;    ("graph-find-node-by-name" "to-string")
;;;;    ("to-string" "to-string")
;;;;    ("to-graphviz" "to-string")
;;;;    ("graph-find-edge-by-name" "to-string")
    ("graph-add-noda-list" "graph-add-noda")
    ("pkg:algorithm" "graph-reorder-vertex")
;;;;    ("pkg:algorithm" "add-vertex")
;;;;    ("pkg:algorithm" "insert")
;;;;    ("pkg:algorithm" "copy-class-instance")
;;;;    ("pkg:algorithm" "switch-time")
    ("pkg:algorithm" "initialize-instance")
    ("pkg:algorithm" "print-object :after ((x ntype) s)")
    ("pkg:algorithm" "print-object :after ((x noda) s)")
    ("pkg:algorithm" "make-create")
    ("pkg:algorithm" "graph-add-noda-list")
    )))

